package com.hp;
// Generated 28-Aug-2016 13:00:28 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Login generated by hbm2java
 */
@Entity
@Table(name="login"
    ,catalog="onlinejobportal"
)
public class Login  implements java.io.Serializable {


     private Integer loginid;
     private String user;
     private String pass;
     private String email;
     private Set<AuthTable> authTables = new HashSet<AuthTable>(0);
    

    public Login() {
    }

	
    public Login(String user, String pass, String email) {
        this.user = user;
        this.pass = pass;
        this.email = email;
    }
    public Login(String user, String pass, String email, Set<AuthTable> authTables) {
       this.user = user;
       this.pass = pass;
       this.email = email;
       this.authTables = authTables;
     
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="loginid", unique=true, nullable=false)
    public Integer getLoginid() {
        return this.loginid;
    }
    
    public void setLoginid(Integer loginid) {
        this.loginid = loginid;
    }

    
    @Column(name="user", nullable=false, length=45)
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }

    
    @Column(name="pass", nullable=false, length=400)
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }

    
    @Column(name="email", nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="login")
    public Set<AuthTable> getAuthTables() {
        return this.authTables;
    }
    
    public void setAuthTables(Set<AuthTable> authTables) {
        this.authTables = authTables;
    }





}


